### ISSUE TITLE
GC memory by Recycler reference counting

### ISSUE THREAD

**Issue by lishuai87** [kentdlee/CoCo#2]
CoCo don't have garbage collection currently,  so we have memory leak.

The PyObject.refCount may help if we call incRef,decRef when we need copy or delete PyObject.
But if we have circular reference,  refCount won't work. 
So we need GC strategy which can handle circular references.  I'm trying to use Recycler:

[1] "A Pure Reference Counting Garbage Collector", 2001, Bacon, D. F., Attanasio, C. R., Rajan, V. T., Smith, S. E., & LEE, H.

https://github.com/thrunduil/cyclic_rc

~~~c++
#include "cyclic_rc/shared_ptr.h"

class PyObject;
using PyObjectPtr = cyclic_rc::shared_ptr<PyObject, false>;

class PyObject : public cyclic_rc::cyclic_rc_base<false> {
 public:
  PyObject();
  virtual ~PyObject();
  virtual void visit_children(int t) override {}
  PyObjectPtr callMethod(PyObjectPtr& my_ptr, string name, vector<PyObjectPtr>* args);
  ...
};

class PyList : public PyObject {
 public:
  void visit_children(int t) override {
    for (auto &i : data) {
      i.visit_children(t);
    }
  }

 protected:
  vector<PyObjectPtr> data;
};

**Comment by kentdlee** [comment]
This repository is for teaching and is an incomplete version of CoCo. A more robust JCoCo version written in Java is available. And, if C++ is your language, a more robust C++ version is available to college/university professors. If you are a college or university professor you can contact me at kentdlee@luther.edu and I will give you access to the full version of CoCo. In this student version which is used as the basis of assignments, garbage collection is not implemented.
